version: "3"

tasks:

  test:
    cmds:
      - poetry run pytest -sv --cov=documentdb tests/ --cov-report=term
  
  test-coverage:
    cmds:
      - poetry run pytest --cov=documentdb tests/ --cov-report=html